# Generated by Django 5.2.13 on 2026-04-08 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The character's display name", max_length=100)),
                ('character_class', models.CharField(choices=[('warrior', 'Warrior'), ('mage', 'Mage'), ('rogue', 'Rogue'), ('healer', 'Healer'), ('ranger', 'Ranger')], default='warrior', help_text="The character's RPG class", max_length=20)),
                ('xp', models.IntegerField(default=0, help_text='Total experience points accumulated', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The player who owns this character', on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The quest title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the quest objectives')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Quest difficulty level (determines XP reward)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the quest is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this quest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('completed', 'Completed')], default='accepted', help_text='Current status of the quest for this player', max_length=10)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the quest was completed', null=True)),
                ('player', models.ForeignKey(help_text='The player who accepted this quest', on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(help_text='The quest that was accepted', on_delete=django.db.models.deletion.CASCADE, related_name='player_quests', to='game.quest')),
            ],
            options={
                'verbose_name': 'Player Quest',
                'verbose_name_plural': 'Player Quests',
                'ordering': ['-accepted_at'],
                'unique_together': {('player', 'quest')},
            },
        ),
    ]
